# Generated by Django 3.0.8 on 2022-06-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
