# Generated by Django 3.0.8 on 2022-06-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='eventattendees',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventattendees',
            name='guest',
        ),
        migrations.DeleteModel(
            name='FoodMenu',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='Bills',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventAttendees',
        ),
    ]
